/**
 * SVG → React Component Generator
 *
 * SEED 식 mono/multicolor 이원화 구조:
 *   svg/mono/        → src/mono/      (currentColor 사용, UI chrome)
 *   svg/multicolor/  → src/multicolor/(브랜드 시그니처, 스타일 잠금)
 *
 * 출력:
 *   - src/mono/{Name}Icon.tsx, src/mono/index.ts, src/mono/vanilla.ts
 *   - src/multicolor/{Name}Icon.tsx, src/multicolor/index.ts, src/multicolor/vanilla.ts
 *   - src/index.ts      : 양쪽 flat re-export + MonoIcons/MultiIcons namespace (백워드 호환)
 *   - src/vanilla.ts    : 양쪽 vanilla 합쳐서 re-export
 *
 * 아이콘 추가 방법:
 *   1. Figma 에서 SVG export
 *   2. svg/mono/ 또는 svg/multicolor/ 에 kebab-case 로 저장
 *   3. pnpm --filter @nudge-design/icons build
 */
const fs = require("fs");
const path = require("path");

const PKG_ROOT = path.join(__dirname, "..");
const SVG_DIR = path.join(PKG_ROOT, "svg");
const SRC_DIR = path.join(PKG_ROOT, "src");
const CATEGORIES = ["mono", "multicolor"];

function toPascalCase(str) {
  return str.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());
}

function svgToComponent(svgContent, componentName) {
  const svgMatch = svgContent.match(/<svg([^>]*)>([\s\S]*?)<\/svg>/);
  if (!svgMatch) throw new Error("Invalid SVG");
  // 소스 viewBox 보존 — 24×24 가 아닌 아이콘(체중계·쿠폰·바텀네비 등)이 잘리지 않게.
  const viewBox = svgMatch[1].match(/\sviewBox="([^"]+)"/)?.[1] ?? "0 0 24 24";
  const innerSvg = svgMatch[2].trim();

  const jsxInner = innerSvg
    .replace(/stroke-width/g, "strokeWidth")
    .replace(/stroke-linecap/g, "strokeLinecap")
    .replace(/stroke-linejoin/g, "strokeLinejoin")
    .replace(/stroke-miterlimit/g, "strokeMiterlimit")
    .replace(/stroke-dasharray/g, "strokeDasharray")
    .replace(/fill-rule/g, "fillRule")
    .replace(/clip-rule/g, "clipRule")
    .replace(/clip-path/g, "clipPath")
    .replace(/gradient-units/g, "gradientUnits")
    .replace(/stop-color/g, "stopColor")
    .replace(/stop-opacity/g, "stopOpacity")
    .replace(/mask-type/g, "maskType")
    .replace(/xmlns:xlink/g, "xmlnsXlink")
    .replace(/xlink:href/g, "xlinkHref")
    .replace(/\s+style="[^"]*"/g, "");

  return `import React from "react";

export interface ${componentName}Props extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
}

export const ${componentName} = React.forwardRef<SVGSVGElement, ${componentName}Props>(
  ({ size = 24, color = "currentColor", ...props }, ref) => (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="${viewBox}"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      color={color}
      {...props}
    >
      ${jsxInner}
    </svg>
  )
);

${componentName}.displayName = "${componentName}";
`;
}

function extractSvgParts(svgContent) {
  const svgMatch = svgContent.match(/<svg([^>]*)>([\s\S]*?)<\/svg>/);
  if (!svgMatch) throw new Error("Invalid SVG");
  const attrs = svgMatch[1];
  const viewBoxMatch = attrs.match(/\sviewBox="([^"]+)"/);
  return {
    viewBox: viewBoxMatch?.[1] ?? "0 0 24 24",
    body: svgMatch[2].trim(),
  };
}

function vanillaModuleContent(exports, options = {}) {
  const { typeName = "VanillaIconName", includeHelpers = false } = options;
  const names = exports.map((e) => e.componentName);
  const typeUnion = names.length
    ? names.map((name) => `  | ${JSON.stringify(name)}`).join("\n")
    : "  never";
  const definitions = exports
    .map(
      (e) =>
        `  ${e.componentName}: {
    viewBox: ${JSON.stringify(e.viewBox)},
    body: ${JSON.stringify(e.body)},
  },`,
    )
    .join("\n");

  const helpers = includeHelpers
    ? `
export const getChevronRightSvg = (options?: VanillaIconOptions): string =>
  getIconSvg("ChevronRightIcon", options);
export const getInfoSvg = (options?: VanillaIconOptions): string => getIconSvg("InfoIcon", options);
export const getTestresultWarningSvg = (options?: VanillaIconOptions): string =>
  getIconSvg("TestresultWarningIcon", options);
export const getThumbUpSvg = (options?: VanillaIconOptions): string =>
  getIconSvg("ThumbUpIcon", options);

export const createChevronRightSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("ChevronRightIcon", options, ownerDocument);
export const createInfoSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("InfoIcon", options, ownerDocument);
export const createTestresultWarningSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("TestresultWarningIcon", options, ownerDocument);
export const createThumbUpSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("ThumbUpIcon", options, ownerDocument);
`
    : "";

  return `// Generated by scripts/generate.cjs. Do not edit directly.

export type ${typeName} =
${typeUnion};

export interface VanillaIconOptions {
  size?: number | string;
  color?: string;
  className?: string;
  title?: string;
  ariaLabel?: string;
  decorative?: boolean;
  attrs?: Record<string, string | number | boolean | null | undefined>;
}

interface IconDefinition {
  viewBox: string;
  body: string;
}

const SVG_NS = "http://www.w3.org/2000/svg";

export const vanillaIconDefinitions: Record<${typeName}, IconDefinition> = {
${definitions}
};

export function getIconSvg(name: ${typeName}, options: VanillaIconOptions = {}): string {
  const definition = vanillaIconDefinitions[name];
  const size = options.size ?? 24;
  const color = options.color ?? "currentColor";
  const attrs = serializeAttrs({
    width: size,
    height: size,
    viewBox: definition.viewBox,
    fill: "none",
    xmlns: SVG_NS,
    color,
    class: options.className,
    role: options.decorative === false || options.ariaLabel || options.title ? "img" : undefined,
    "aria-label": options.ariaLabel,
    "aria-hidden": options.decorative === false || options.ariaLabel || options.title ? undefined : "true",
    ...options.attrs,
  });
  const title = options.title ? \`<title>\${escapeText(options.title)}</title>\` : "";
  return \`<svg\${attrs}>\${title}\${definition.body}</svg>\`;
}

export function createIconSvg(
  name: ${typeName},
  options: VanillaIconOptions = {},
  ownerDocument: Document | undefined = globalThis.document,
): SVGSVGElement {
  if (!ownerDocument) {
    throw new Error("createIconSvg requires a DOM Document.");
  }
  const template = ownerDocument.createElement("template");
  template.innerHTML = getIconSvg(name, options).trim();
  const svg = template.content.firstElementChild;
  if (!svg || svg.namespaceURI !== SVG_NS || svg.localName !== "svg") {
    return ownerDocument.createElementNS(SVG_NS, "svg");
  }
  return svg as SVGSVGElement;
}
${helpers}
function serializeAttrs(attrs: Record<string, string | number | boolean | null | undefined>): string {
  return Object.entries(attrs)
    .filter(([, value]) => value !== null && value !== undefined && value !== false)
    .map(([name, value]) => {
      if (value === true) return \` \${name}\`;
      return \` \${name}="\${escapeAttr(String(value))}"\`;
    })
    .join("");
}

function escapeAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeText(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
`;
}

function rimrafSync(target) {
  if (!fs.existsSync(target)) return;
  for (const entry of fs.readdirSync(target)) {
    const full = path.join(target, entry);
    const stat = fs.lstatSync(full);
    if (stat.isDirectory()) rimrafSync(full);
    else fs.unlinkSync(full);
  }
  fs.rmdirSync(target);
}

function buildCategory(category) {
  const svgCategoryDir = path.join(SVG_DIR, category);
  const srcCategoryDir = path.join(SRC_DIR, category);

  rimrafSync(srcCategoryDir);
  fs.mkdirSync(srcCategoryDir, { recursive: true });

  const exports = [];
  if (!fs.existsSync(svgCategoryDir)) return exports;

  const svgFiles = fs
    .readdirSync(svgCategoryDir)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  for (const file of svgFiles) {
    const name = file.replace(".svg", "");
    const componentName = toPascalCase(name) + "Icon";
    const svgContent = fs.readFileSync(path.join(svgCategoryDir, file), "utf-8");

    const component = svgToComponent(svgContent, componentName);
    const svgParts = extractSvgParts(svgContent);
    const outFile = `${componentName}.tsx`;

    fs.writeFileSync(path.join(srcCategoryDir, outFile), component);
    exports.push({ componentName, outFile, ...svgParts });
  }

  // category index.ts
  const indexContent =
    exports
      .map((e) => `export { ${e.componentName} } from "./${e.outFile.replace(".tsx", ".js")}";`)
      .join("\n") +
    "\n" +
    exports
      .map(
        (e) => `export type { ${e.componentName}Props } from "./${e.outFile.replace(".tsx", ".js")}";`,
      )
      .join("\n") +
    "\n";
  fs.writeFileSync(path.join(srcCategoryDir, "index.ts"), indexContent);

  // category vanilla.ts (mono only ships convenience helpers)
  fs.writeFileSync(
    path.join(srcCategoryDir, "vanilla.ts"),
    vanillaModuleContent(exports, {
      typeName: `Vanilla${category === "mono" ? "Mono" : "Multi"}IconName`,
      includeHelpers: category === "mono",
    }),
  );

  return exports;
}

function writeRootIndex(monoExports, multiExports) {
  const lines = [];
  lines.push(`// Generated by scripts/generate.cjs. Do not edit directly.`);
  lines.push(``);
  lines.push(`// Backward-compatible flat re-exports.`);
  for (const e of monoExports) {
    lines.push(
      `export { ${e.componentName} } from "./mono/${e.outFile.replace(".tsx", ".js")}";`,
    );
  }
  for (const e of multiExports) {
    lines.push(
      `export { ${e.componentName} } from "./multicolor/${e.outFile.replace(".tsx", ".js")}";`,
    );
  }
  for (const e of monoExports) {
    lines.push(
      `export type { ${e.componentName}Props } from "./mono/${e.outFile.replace(".tsx", ".js")}";`,
    );
  }
  for (const e of multiExports) {
    lines.push(
      `export type { ${e.componentName}Props } from "./multicolor/${e.outFile.replace(".tsx", ".js")}";`,
    );
  }
  lines.push(``);
  lines.push(`// Namespaced exports (SEED-style mono/multicolor separation).`);
  lines.push(`export * as MonoIcons from "./mono/index.js";`);
  lines.push(`export * as MultiIcons from "./multicolor/index.js";`);
  lines.push(``);
  fs.writeFileSync(path.join(SRC_DIR, "index.ts"), lines.join("\n"));
}

function writeRootVanilla(monoExports, multiExports) {
  const merged = [...monoExports, ...multiExports];
  fs.writeFileSync(
    path.join(SRC_DIR, "vanilla.ts"),
    vanillaModuleContent(merged, { typeName: "VanillaIconName", includeHelpers: true }),
  );
}

function cleanLegacyFlatFiles() {
  // 이전 flat 구조에서 src/ 직속에 있던 *.tsx 와 vanilla.ts 잔재 제거
  for (const entry of fs.readdirSync(SRC_DIR)) {
    if (entry === "mono" || entry === "multicolor") continue;
    if (entry.endsWith(".tsx") || entry === "vanilla.ts" || entry === "index.ts") {
      fs.unlinkSync(path.join(SRC_DIR, entry));
    }
  }
}

function main() {
  if (!fs.existsSync(SRC_DIR)) fs.mkdirSync(SRC_DIR, { recursive: true });
  cleanLegacyFlatFiles();

  const results = {};
  for (const category of CATEGORIES) {
    results[category] = buildCategory(category);
    console.log(`  ✓ ${category}: ${results[category].length} icons`);
  }

  writeRootIndex(results.mono, results.multicolor);
  writeRootVanilla(results.mono, results.multicolor);

  const total = results.mono.length + results.multicolor.length;
  console.log(
    `\n  Generated ${total} icons (${results.mono.length} mono, ${results.multicolor.length} multicolor)`,
  );
}

main();
