/**
 * SVG → React Component Generator
 *
 * svg/ 폴더의 모든 .svg 파일을 읽어서 src/ 에 React 컴포넌트로 생성합니다.
 * 외부 의존성 없이 순수 Node.js로 동작합니다.
 *
 * 사용법: node scripts/generate.js
 *
 * 아이콘 추가 방법:
 *   1. Figma에서 아이콘을 SVG로 export
 *   2. svg/ 폴더에 kebab-case 이름으로 저장 (예: chevron-right.svg)
 *   3. pnpm --filter @nudge-eap/icons build
 */
const fs = require("fs");
const path = require("path");

const SVG_DIR = path.join(__dirname, "..", "svg");
const SRC_DIR = path.join(__dirname, "..", "src");

// kebab-case → PascalCase
function toPascalCase(str) {
  return str.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());
}

// SVG string → React component string
function svgToComponent(svgContent, componentName) {
  // Extract inner content of <svg> tag
  const svgMatch = svgContent.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!svgMatch) throw new Error("Invalid SVG");

  const innerSvg = svgMatch[1].trim();

  // Convert SVG attributes to JSX
  const jsxInner = innerSvg
    .replace(/stroke-width/g, "strokeWidth")
    .replace(/stroke-linecap/g, "strokeLinecap")
    .replace(/stroke-linejoin/g, "strokeLinejoin")
    .replace(/stroke-miterlimit/g, "strokeMiterlimit")
    .replace(/stroke-dasharray/g, "strokeDasharray")
    .replace(/fill-rule/g, "fillRule")
    .replace(/clip-rule/g, "clipRule")
    .replace(/clip-path/g, "clipPath")
    .replace(/mask-type/g, "maskType")
    .replace(/xmlns:xlink/g, "xmlnsXlink")
    .replace(/xlink:href/g, "xlinkHref")
    // Strip plain string style attrs — JSX requires style={{...}}, not style="..."
    .replace(/\s+style="[^"]*"/g, "");

  return `import React from "react";

export interface ${componentName}Props extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
}

export const ${componentName} = React.forwardRef<SVGSVGElement, ${componentName}Props>(
  ({ size = 24, color = "currentColor", ...props }, ref) => (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      color={color}
      {...props}
    >
      ${jsxInner}
    </svg>
  )
);

${componentName}.displayName = "${componentName}";
`;
}

function extractSvgParts(svgContent) {
  const svgMatch = svgContent.match(/<svg([^>]*)>([\s\S]*?)<\/svg>/);
  if (!svgMatch) throw new Error("Invalid SVG");

  const attrs = svgMatch[1];
  const viewBoxMatch = attrs.match(/\sviewBox="([^"]+)"/);
  return {
    viewBox: viewBoxMatch?.[1] ?? "0 0 24 24",
    body: svgMatch[2].trim(),
  };
}

function vanillaModuleContent(exports) {
  const names = exports.map((e) => e.componentName);
  const typeUnion = names.map((name) => `  | ${JSON.stringify(name)}`).join("\n");
  const definitions = exports
    .map(
      (e) =>
        `  ${e.componentName}: {
    viewBox: ${JSON.stringify(e.viewBox)},
    body: ${JSON.stringify(e.body)},
  },`,
    )
    .join("\n");

  return `// Generated by scripts/generate.js. Do not edit directly.

export type VanillaIconName =
${typeUnion};

export interface VanillaIconOptions {
  size?: number | string;
  color?: string;
  className?: string;
  title?: string;
  ariaLabel?: string;
  decorative?: boolean;
  attrs?: Record<string, string | number | boolean | null | undefined>;
}

interface IconDefinition {
  viewBox: string;
  body: string;
}

const SVG_NS = "http://www.w3.org/2000/svg";

export const vanillaIconDefinitions: Record<VanillaIconName, IconDefinition> = {
${definitions}
};

export function getIconSvg(name: VanillaIconName, options: VanillaIconOptions = {}): string {
  const definition = vanillaIconDefinitions[name];
  const size = options.size ?? 24;
  const color = options.color ?? "currentColor";
  const attrs = serializeAttrs({
    width: size,
    height: size,
    viewBox: definition.viewBox,
    fill: "none",
    xmlns: SVG_NS,
    color,
    class: options.className,
    role: options.decorative === false || options.ariaLabel || options.title ? "img" : undefined,
    "aria-label": options.ariaLabel,
    "aria-hidden": options.decorative === false || options.ariaLabel || options.title ? undefined : "true",
    ...options.attrs,
  });
  const title = options.title ? \`<title>\${escapeText(options.title)}</title>\` : "";
  return \`<svg\${attrs}>\${title}\${definition.body}</svg>\`;
}

export function createIconSvg(
  name: VanillaIconName,
  options: VanillaIconOptions = {},
  ownerDocument: Document | undefined = globalThis.document,
): SVGSVGElement {
  if (!ownerDocument) {
    throw new Error("createIconSvg requires a DOM Document.");
  }
  const template = ownerDocument.createElement("template");
  template.innerHTML = getIconSvg(name, options).trim();
  const svg = template.content.firstElementChild;
  if (!svg || svg.namespaceURI !== SVG_NS || svg.localName !== "svg") {
    return ownerDocument.createElementNS(SVG_NS, "svg");
  }
  return svg as SVGSVGElement;
}

export const getChevronRightSvg = (options?: VanillaIconOptions): string =>
  getIconSvg("ChevronRightIcon", options);
export const getInfoSvg = (options?: VanillaIconOptions): string => getIconSvg("InfoIcon", options);
export const getTestresultWarningSvg = (options?: VanillaIconOptions): string =>
  getIconSvg("TestresultWarningIcon", options);
export const getThumbUpSvg = (options?: VanillaIconOptions): string =>
  getIconSvg("ThumbUpIcon", options);

export const createChevronRightSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("ChevronRightIcon", options, ownerDocument);
export const createInfoSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("InfoIcon", options, ownerDocument);
export const createTestresultWarningSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("TestresultWarningIcon", options, ownerDocument);
export const createThumbUpSvg = (
  options?: VanillaIconOptions,
  ownerDocument?: Document,
): SVGSVGElement => createIconSvg("ThumbUpIcon", options, ownerDocument);

function serializeAttrs(attrs: Record<string, string | number | boolean | null | undefined>): string {
  return Object.entries(attrs)
    .filter(([, value]) => value !== null && value !== undefined && value !== false)
    .map(([name, value]) => {
      if (value === true) return \` \${name}\`;
      return \` \${name}="\${escapeAttr(String(value))}"\`;
    })
    .join("");
}

function escapeAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeText(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
`;
}

// Main
function main() {
  if (!fs.existsSync(SRC_DIR)) fs.mkdirSync(SRC_DIR, { recursive: true });

  const svgFiles = fs.readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg"));
  const exports = [];

  for (const file of svgFiles) {
    const name = file.replace(".svg", "");
    const componentName = toPascalCase(name) + "Icon";
    const svgContent = fs.readFileSync(path.join(SVG_DIR, file), "utf-8");

    const component = svgToComponent(svgContent, componentName);
    const svgParts = extractSvgParts(svgContent);
    const outFile = `${componentName}.tsx`;

    fs.writeFileSync(path.join(SRC_DIR, outFile), component);
    exports.push({ componentName, outFile, ...svgParts });

    console.log(`  ✓ ${file} → ${outFile}`);
  }

  // Generate index.ts
  const indexContent =
    exports
      .map((e) => `export { ${e.componentName} } from "./${e.outFile.replace(".tsx", "")}";`)
      .join("\n") +
    "\n" +
    exports
      .map(
        (e) => `export type { ${e.componentName}Props } from "./${e.outFile.replace(".tsx", "")}";`,
      )
      .join("\n") +
    "\n";

  fs.writeFileSync(path.join(SRC_DIR, "index.ts"), indexContent);
  fs.writeFileSync(path.join(SRC_DIR, "vanilla.ts"), vanillaModuleContent(exports));

  console.log(`\n  Generated ${exports.length} icon components + index.ts + vanilla.ts`);
}

main();
